/*
 *  	Created on: 22/11/2023
 *      LAYER : MCAL
 *      Author: Mohamed sarary
 *      File  : RCC_Program.c
 */

#include "ErrorStates.h"
#include "StdTypes.h"
#include "BitMath.h"

#include "RCC_Interface.h"
#include "RCC_Private.h"
#include "RCC_Config.h"


void RCC_voidClockInit(void)
{

#if SYS_CLOCK == HSI
	SET_BIT(MRCC->RCC_CR,CR_HSI_ON);					/* TURN ON HSI */
	//while( !(GET_BIT(MRCC->RCC_CR,CR_HSI_RDY)) );		/* WAIT TILL HSI IS READY */
	CLR_BIT(MRCC->RCC_CFGR,CFGR_SW0);					/* CHOOSE HSI */
	CLR_BIT(MRCC->RCC_CFGR,CFGR_SW1);

#elif SYS_CLOCK == HSE_CRYSTAL
	SET_BIT(MRCC->RCC_CR,CR_HSE_ON);					/* TURN ON HSE */
	while( !(GET_BIT(MRCC->RCC_CR,CR_HSE_RDY)) );		/* WAIT TILL HSE IS READY */
	CLR_BIT(MRCC->RCC_CR,CR_HSEBYP);					/* DISABLE BYPASS */
	SET_BIT(MRCC->RCC_CFGR,CFGR_SW0);					/* CHOOSE HSE */
	CLR_BIT(MRCC->RCC_CFGR,CFGR_SW1);

#elif SYS_CLOCK == HSE_RC
	SET_BIT(MRCC->RCC_CR,CR_HSE_ON);					/* TURN ON HSE */
	while( !(GET_BIT(MRCC->RCC_CR,CR_HSE_RDY)) );		/* WAIT TILL HSE IS READY */
	SET_BIT(MRCC->RCC_CR,CR_HSE_BYP);					/* DISABLE BYPASS */
	SET_BIT(MRCC->RCC_CFGR,CFGR_SW0);					/* CHOOSE HSE */
	CLR_BIT(MRCC->RCC_CFGR,CFGR_SW1);

#elif SYS_CLOCK == PLL
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PLLMUL0);								 /* CLEAR MULTIPLICATION BITS */
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PLLMUL1);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PLLMUL2);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PLLMUL3);
	MRCC->RCC_CFGR |= ( (PLL_MUL_FACTOR - 2) << CFGR_PLLMUL0 ) ;		/* ADD THE NEW MULTIPLICATION VALUE */

#if PLL_SOURCE == HSI_DIV2
	SET_BIT(MRCC->RCC_CR,CR_HSI_ON);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PLLSRC);
#elif PLL_SOURCE == HSE
	SET_BIT(MRCC->RCC_CR,CR_HSE_ON);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PLLSRC);
#elif PLL_SOURCE == HSE_DIV2
	SET_BIT(MRCC->RCC_CR,CR_HSE_ON);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PLLXTPRE);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PLLSRC);
#else
#error "WRONG PLL SOURCE"
#endif

	while( !(GET_BIT(MRCC->RCC_CR,CR_PLL_RDY)) );		/* WAIT TILL PLL IS READY */
	SET_BIT(MRCC->RCC_CR,CR_PLL_ON);					/* TURN ON PLL */
	CLR_BIT(MRCC->RCC_CFGR,CFGR_SW0);					/* CHOOSE PLL */
	SET_BIT(MRCC->RCC_CFGR,CFGR_SW1);
#else
#error "WRONG SYSTEM CLOCK CHOICE"
#endif


#if MCO_STATE == NoClock
	CLR_BIT(MRCC->RCC_CFGR,CFGR_MCO2);
#elif MCO_STATE == SYSCLk_OUTPUT
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_MCO1);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_MCO2);
#elif MCO_STATE == HSI_OUTPUT
	SET_BIT(MRCC->RCC_CR,CR_HSI_ON);					/* TURN ON HSI */
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_MCO1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO2);
#elif MCO_STATE == HSE_OUTPUT
	SET_BIT(MRCC->RCC_CR,CR_HSE_ON);					/* TURN ON HSE */
	CLR_BIT(MRCC->RCC_CFGR,CFGR_MCO0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO2);
#elif MCO_STATE == PLL_OUTPUT
	SET_BIT(MRCC->RCC_CR,CR_PLL_ON);					/* TURN ON PLL */
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_MCO2);
#else
#error "WRONG MICROCONTROLLER CLOCK OUTPUT CHOICE"
#endif


#if CCS_STATE == DISABLE
	CLR_BIT(MRCC->RCC_CR,CR_CSS_ON);
#elif CSS_STATE == ENABLE
	SET_BIT(MRCC->RCC_CR,CR_CSS_ON);
#else
#error "WRONG SECUITY SYSTEM CHOICE"
#endif

	/* CHOOSING SIUTABLE PRESCALLER FOR AHB BUS */
#if RCC_AHB_PRESCALLER == RCC_PRESCALLER_0
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_2
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_4
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_8
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_16
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_64
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_128
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_265
	CLR_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#elif RCC_AHB_PRESCALLER == RCC_PRSCALLER_512
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE2);
	SET_BIT(MRCC->RCC_CFGR,CFGR_HPRE3);
#else
#error "WRONG AHB BUS PRESCALLER CHOICE"
#endif

	/* CHOOSING SIUTABLE PRESCALLER FOR APB1 BUS */
#if RCC_APB1_PRESCALLER == RCC_PRESCALLER_0
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALLER == RCC_PRESCALLER_2
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALLER == RCC_PRESCALLER_4
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALLER == RCC_PRESCALLER_8
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_2);
#elif RCC_APB1_PRESCALLER == RCC_PRESCALLER_16
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE1_2);
#else
#error "WRONG APB1 BUS PRESCALLER CHOICE"

#endif

	/* CHOOSING SIUTABLE PRESCALLER FOR APB2 BUS */
#if RCC_APB2_PRESCALLER == RCC_PRESCALLER_0
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_2);
#elif RCC_APB2_PRESCALLER == RCC_PRESCALLER_2
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_2);
#elif RCC_APB2_PRESCALLER == RCC_PRESCALLER_4
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_2);
#elif RCC_APB2_PRESCALLER == RCC_PRESCALLER_8
	CLR_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_2);
#elif RCC_APB2_PRESCALLER == RCC_PRESCALLER_16
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_1);
	SET_BIT(MRCC->RCC_CFGR,CFGR_PPRE2_2);
#else
#error "WRONG APB2 BUS PRESCALLER CHOICE"
#endif


	/* CHOOSING SIUTABLE PRESCALLER FOR ADC */
#if ADC_PRESCALLER == RCC_PRESCALLER_2
	CLR_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE1);
#elif ADC_PRESCALLER == RCC_PRESCALLER_4
	SET_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE0);
	CLR_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE1);
#elif ADC_PRESCALLER == RCC_PRESCALLER_6
	CLR_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE1);
#elif ADC_PRESCALLER == RCC_PRESCALLER_8
	SET_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE0);
	SET_BIT(MRCC->RCC_CFGR,CFGR_ADCPRE1);
#else
#error "WRONG ADC PRESCALLER CHOICE"
#endif
}


u8 RCC_u8PeriheralEnable( u8 Copy_u8BusID , u8 Copy_u8PeriheralID)
{
	u8 Local_u8FuncState = FuncNOK ;
	if(Copy_u8PeriheralID <= 31 )
	{
		switch (Copy_u8BusID)
		{
		case AHB  : SET_BIT( MRCC->RCC_AHBENR  , Copy_u8PeriheralID );
		Local_u8FuncState = FuncOK ;
		break;

		case APB1 :	SET_BIT( MRCC->RCC_APB1ENR , Copy_u8PeriheralID );
		Local_u8FuncState = FuncOK ;
		break;

		case APB2 : SET_BIT( MRCC->RCC_APB2ENR , Copy_u8PeriheralID );
		Local_u8FuncState = FuncOK ;
		break;

		default :
			Local_u8FuncState = FuncNOK ;
			break;
		}
	}
	return Local_u8FuncState ;
}


u8 RCC_u8PeriheralDisable( u8 Copy_u8BusID , u8 Copy_u8PeriheralID)
{
	u8 Local_u8FuncState = FuncNOK ;
	if(Copy_u8PeriheralID <= 31 )
	{
		switch (Copy_u8BusID)
		{
		case AHB  : CLR_BIT( MRCC->RCC_AHBENR  , Copy_u8PeriheralID );
		Local_u8FuncState = FuncOK ;
		break;

		case APB1 :	CLR_BIT( MRCC->RCC_APB1ENR , Copy_u8PeriheralID );
		Local_u8FuncState = FuncOK ;
		break;

		case APB2 : CLR_BIT( MRCC->RCC_APB2ENR , Copy_u8PeriheralID );
		Local_u8FuncState = FuncOK ;
		break;

		default :
			Local_u8FuncState = FuncNOK ;
			break;
		}
	}
	return Local_u8FuncState ;
}
